### ISSUE TITLE
[Umbrella issue] Problems with DigitalOcean clusters

### ISSUE THREAD

**Issue by xmudrii** [kubicorn/kubicorn#587]
Currently, you can't create DigitalOcean clusters because of several bugs.
This issue is an umbrella issue for collecting what problems are currently present.

* [x] Firewall gets created before Droplets, so tags are not created, causing `kubicorn` to fail.
```
2018-03-14T07:17:40+01:00 [▶]  Actual   : e466da0f429622cb75f60ba2a13f7856
2018-03-14T07:17:40+01:00 [▶]  Expected : 7b61fa7dbd895f946758902de93e70c9
2018-03-14T07:17:41+01:00 [✖]  Error during apply of atomic reconciler, attempting clawback: failed to create the firewall err: POST https://api.digitalocean.com/v2/firewalls: 422 (request "c453e954-81f7-4a56-ba78-b97d1464b069") tag testing-master does not exist
2018-03-14T07:17:41+01:00 [!]  
2018-03-14T07:17:41+01:00 [!]  Attempting to backtrack and cleanup created resources.
2018-03-14T07:17:41+01:00 [!]  
2018-03-14T07:17:41+01:00 [▶]  droplet.Delete
```
Temporarily, this can be resolved by creating tags using API, or CLI (e.g. `doctl compute tag create <name>`).
* [x] Actual and Expected states are the same, causing Droplets to never get created (reconcile is skipped). Even if you create tags, due to described problem, `kubicorn` will never create Droplets, actually, it will exit [here](https://github.com/kubicorn/kubicorn/blob/master/cloud/digitalocean/droplet/resources/droplet.go#L119). This can be fixed by missing something on purpose in Actual or Expected.
* [x] Region is not set, causing DigitalOcean API to fail.
```
2018-03-15T21:39:08+01:00 [▶]  Expected : 6bdf68562f35856ab108efdadedeb621
2018-03-15T21:39:08+01:00 [ℹ]  Parsing bootstrap script from GitHub [https://raw.githubusercontent.com/kubicorn/kubicorn/master/bootstrap/vpn/openvpnMaster.sh]
2018-03-15T21:39:08+01:00 [ℹ]  Parsing bootstrap script from GitHub [https://raw.githubusercontent.com/kubicorn/kubicorn/master/bootstrap/digitalocean_k8s_ubuntu_16.04_master.sh]
&resources.Droplet{Shared:resources.Shared{CloudID:"", Name:"testing-master", Tags:[]string(nil)}, Region:"", Size:"s-2vcpu-2gb", Image:"ubuntu-16-04-x64", Count:1, SSHFingerprint:"2b:5f:9a:3a:4f:4f:78:66:8e:cb:c3:8d:b3:31:45:be", BootstrapScripts:[]string{"bootstrap/vpn/openvpnMaster.sh", "bootstrap/digitalocean_k8s_ubuntu_16.04_master.sh"}, ServerPool:(*cluster.ServerPool)(nil)}
2018-03-15T21:39:09+01:00 [✖]  Error during apply of atomic reconciler, attempting clawback: POST https://api.digitalocean.com/v2/droplets: 422 You specified an invalid region for Droplet creation.
2018-03-15T21:39:09+01:00 [!]  
2018-03-15T21:39:09+01:00 [!]  Attempting to backtrack and cleanup created resources.
2018-03-15T21:39:09+01:00 [!]  
```
* [x] The `masterTag` variable used to obtain Master IP via API is not set. This could be due to that `serverPool.Type` is always empty string ([here](https://github.com/kubicorn/kubicorn/blob/master/cloud/digitalocean/droplet/resources/droplet.go#L133)).
* [x] We're incorrectly filling fields, such as [this one](https://github.com/kubicorn/kubicorn/blob/master/cloud/digitalocean/droplet/resources/droplet.go#L191).
The correct way is:
```
providerConfig := something.ProviderConfig()
providerConfig.other = what
something.SetProviderConfig(providerConfig)
```

**Comment by xmudrii** [comment]
#592 fixes this issues.
